[package]
name = "drop-point"
version = "0.0.1"
edition = "2024"
description = "Remote cargo cache, part of rargo"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/sadosystems/rargo"

[dependencies]
log.workspace = true
env_logger.workspace = true
thiserror.workspace = true
blake3.workspace = true
tempfile.workspace = true
zip.workspace = true
zstd.workspace = true